java.version=${javaVersion}
archetype.version=${archetypeVersion}
lombok.version=${lombokVersion}
errorprone.core.version=${errorproneCoreVersion}
nullaway.version=${nullawayVersion}
jspecify.version=${jspecifyVersion}